from enum import Enum


class Player(Enum):
    red = 0
    green = 1
    yellow = 2
    blue = 3



CELL_SIZE_PX = 36
BOARD_SIZE_CELLS = 20
BOARD_SIZE_PX = BOARD_SIZE_CELLS * CELL_SIZE_PX
DIVIDER_WIDTH_PX = 36
PICKER_HEIGHT_OFFSET_PX = 2 * CELL_SIZE_PX
PICKER_WIDTH_OFFSET_PX = BOARD_SIZE_PX + DIVIDER_WIDTH_PX
PICKER_CELL_SIZE_PX = 13
PICKER_ROWS = 13
PICKER_COLS = 12
PICKER_HEIGHT_PX = PICKER_ROWS * PICKER_CELL_SIZE_PX
PICKER_WIDTH_PX = PICKER_COLS * PICKER_CELL_SIZE_PX
CANVAS_WIDTH_PX = (BOARD_SIZE_CELLS * CELL_SIZE_PX) + (PICKER_COLS * PICKER_CELL_SIZE_PX) + DIVIDER_WIDTH_PX + 350
CANVAS_HEIGHT_PX = BOARD_SIZE_CELLS * CELL_SIZE_PX + 350
